#!/bin/sh
#
# @name SDU Drone
#
# @type Hexarotor x
#

. ${R}etc/init.d/rc.mc_defaults

param set-default MAV_TYPE 13

param set NAV_DLL_ACT 0
param set NAV_RCL_ACT 0
param set COM_OBL_ACT 0

param set EKF2_AID_MASK 1
param set EKF2_HGT_MODE 0
param set EKF2_EV_DELAY 50

set MIXER hexa_x_sdu
